[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
target-version = "py311"
line-length = 88
select = [
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "B",   # flake8-bugbear
    "I",   # isort
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # Line length handled by Black
]

[tool.ruff.lint]
preview = false

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["app"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
no_implicit_optional = true
check_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = ["app.*"]
strict = true
